language: cpp
dist: xenial
before_script:
- sudo apt-add-repository -y "deb http://archive.ubuntu.com/ubuntu xenial main universe"
- sudo add-apt-repository -y "ppa:ubuntu-toolchain-r/test"
- sudo apt-get update
- sudo apt-get install -y libgtest-dev build-essential cmake clang-6.0 gcc-8 g++-8
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 60 --slave /usr/bin/g++ g++ /usr/bin/g++-8
- pushd /usr/src/gtest
- sudo cmake .
- sudo cmake --build . -- -j "`nproc`"
- sudo cp *.a /usr/lib
- popd
script:
- cmake -D BUILD_TYPE_RELEASE=ON .
- cmake --build . -- -j "`nproc`"
- cmake --build . --target test -- -j "`nproc`"
- cmake --build . --target package -- -j "`nproc`"
deploy:
  provider: script
  skip_cleanup: true
  debug: on
  script:
    - curl -T "allocator_0.0.${TRAVIS_BUILD_NUMBER}_amd64.deb" -u edwdmkrv:"$BINTRAY_API_KEY" "https://api.bintray.com/content/edwdmkrv/allocator/allocator/0.0.${TRAVIS_BUILD_NUMBER}/pool/main/a/allocator/allocator_0.0.${TRAVIS_BUILD_NUMBER}_amd64.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
